services:
  - type: web
    name: examination-system
    runtime: php
    region: singapore
    plan: free
    buildCommand: composer install --optimize-autoloader --no-dev && chmod -R 775 storage bootstrap/cache
    startCommand: php artisan migrate --force && php artisan db:seed --class=AdminSeeder --force && php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_NAME
        value: Examination Management System
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:sfmJWnDSXwPdUEmarOa0y4h1vTbNfRURwyhK4jQ2VSM=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: examination-system-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: examination-system-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: examination-system-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: examination-system-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: examination-system-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: FORCE_HTTPS
        value: true
      - key: QUEUE_CONNECTION
        value: sync
      - key: SANCTUM_STATEFUL_DOMAINS
        value: examination-system-uzqp.onrender.com
      - key: APP_URL
        value: https://examination-system-uzqp.onrender.com

databases:
  - name: examination-system-db
    databaseName: examination_db
    user: examination_user
    region: singapore
    plan: free
