services:
  - type: web
    name: examination-system
    env: docker
    region: singapore
    plan: free
    buildCommand: composer install --optimize-autoloader --no-dev && php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan db:seed --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && chmod -R 775 storage bootstrap/cache
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_NAME
        value: Examination Management System
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:sfmJWnDSXwPdUEmarOa0y4h1vTbNfRURwyhK4jQ2VSM=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: examination-system-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: examination-system-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: examination-system-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: examination-system-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: examination-system-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_SECURE_COOKIES
        value: true
      - key: FORCE_HTTPS
        value: true
      - key: APP_URL
        value: https://examination-system-uzqp.onrender.com
